[build]
  command = "yarn run build" # Comando para construir tu sitio
  publish = "dist" # Directorio que contiene tu sitio construido
  functions = "netlify/functions" # Directorio que contiene tus funciones