# netlify.toml
[build]
  command = "yarn run build"
  publish = "dist"

[dependencies]
  bcrypt = "*"

[dev]
  command = "yarn run dev"
  port = 8888
  publish = "out"
  targetPort = 4321

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4321/api/:splat"
  status = 200
  force = true